#!/usr/bin/env bash
. ./setupQuery

# used in route /courses/[id]
# echo ${query[id]}

if [ "${query_subject}" == "all" ]; then
    query "courses.json" | `tool courses`
else
    query "courses/${query_subject}/${query_number}.json" | `tool course-info`
fi

