#!/usr/bin/env bash
. ./setupQuery

# used in route /courses/[id]
# echo ${query[id]}

if [ "${query_id}" == "all" ]; then
    query "courses.json" | `tool courses`
else
    query "courses/${query_id}.json" | `tool course-info`
fi

