#!/usr/bin/env bash

echo "Content-Type: text/plain"
echo

saveIFS=$IFS
IFS='=&'
parm=($QUERY_STRING)
IFS=$saveIFS


declare -A query
for ((i=0; i<${#parm[@]}; i+=2))
do
    query[${parm[i]}]=${parm[i+1]}
done
